#!/usr/bin/env bash

WALLDIR="$HOME/Wallpapers"

choice=$(find "$WALLDIR" -maxdepth 1 -type f \
  | awk -F/ '{print $NF "\0icon\x1f" $0}' \
  | wofi \
      --dmenu \
      --show-icons \
      --prompt "Wallpaper")

[ -z "$choice" ] && exit 0

set-wallpaper "$WALLDIR/$choice"