#!/usr/bin/env bash

WALLDIR="$HOME/Wallpapers"

choice=$(ls "$WALLDIR" | wofi \
  --dmenu \
  --prompt "Search for a Wallpaper...")

[ -z "$choice" ] && exit 0

# set the selected wallpaper
set-wallpaper "$WALLDIR/$choice"