import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`main-layout ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Container to make the navbar fixed */}
        <div className="z-50 fixed top-5 w-full px-2 flex justify-center bg-transparent items-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
