#!/usr/bin/env bash

WALLDIR="$HOME/Wallpapers"

choice=$(ls "$WALLDIR" | wofi \
  --dmenu --prompt "Wallpaper")

[ -z "$choice" ] && exit 0

# set the selected wallpaper
set-wallpaper "$WALLDIR/$choice"