#!/usr/bin/env bash

WALLDIR="$HOME/Wallpapers"

choice=$(ls "$WALLDIR" | wofi --dmenu --allow-images --allow-markup --prompt "Wallpaper")

[ -z "$choice" ] && exit 0

# set the selected wallpaper
set-wallpaper "$WALLDIR/$choice"